### ISSUE TITLE
Connecting Geometry between Entrance Tank and Filter

### ISSUE THREAD

**Issue by MattCimini** [AguaClara/aide_template-DEPRECATED#11]
Have the geometry that can connect all of the pipes inside the filter to the pipe stubs 
- parameterize according to distance betwwen these two objects
- talk to Draw about coordinate system

**Comment by eak24** [comment]
Explain coordinate system you want to implement please!

**Comment by MattCimini** [comment]
The basic idea to get locations of the pipe stubs in the entrance tank was to use an origin defined in the corner of the entrance tank as well as x & y locations to define where the pipes are relative to that point..

![image](https://user-images.githubusercontent.com/35536127/37486166-0c0f5672-2864-11e8-9fe1-9e1f2377f2cb.png)

This can be seen in the Template parameter google sheets.

This is our first working idea, but are open to finding something more elegant possibly

**Comment by eak24** [comment]
I'm not sure I understand. Are you referring to developing a new origin? I don't think I'm understanding the function of this... I would think that the filter box pipe stub locations should be defined by a collection of variables. How is this different than anything else? You'll need to be very careful about pipe lengths and properly changing those, but otherwise, I fail to see the key difference. Are you trying to account for varying walkway lengths? If so, why not include that as a variable?

**Comment by MattCimini** [comment]
@ethan92429 I'm sure we can discuss this more in length at our meeting, but the basic idea behind the coordinate system is to get the displacements of the beginning of the pipe. In order to make the appropriate lengths of pipes we need to know the distance from the entrance tank to the filter. To do this we made a locally defined origin at the corner of the entrance tank. This way if the entrance tank moves for some reason (e.g. walkways) the pipes will also move. This variable is known as "Filter_TankEntrance_Distance"
