### ISSUE TITLE
link to Fusion Templates

### ISSUE THREAD

**Issue by monroews** [AguaClara/aide_template-DEPRECATED#20]
Provide directions in your wiki (here in Github) for how to view your templates in Fusion.  I assume these are available in the cloud and that you could provide a hyperlink.

Is it possible to make the Fusion templates open source so that anyone can view them while still keeping them secure for the team to control changes?

**Comment by eak24** [comment]
Yes - you can just share [public links](https://www.autodesk.com/products/fusion-360/blog/share-a-public-link-of-your-fusion-360-design/) For example, here is our [flocculator](https://a360.co/2JSmApK) Note that you cannot modify that design. What's more complex is providing a downloadable model that can be 'designed'. Unfortunately the only way to get a full assembly through Fusion is to have it sent to your email. Therefore we need to store our finished templates in a Github repo (not on the Autodesk cloud). This will allow us to auto-download the 3D model to then scale it appropriately.

**Comment by MattCimini** [comment]
Because the hyperlinks can only be created for individual assemblies there is no way to post a single link that can give viewing access to all the parts of the plant without assembling the whole plant first. So I can either do 1 of 2 things:
1. I could post a list of a bunch of viewable components, so one for the flocculator, another for the filter, another for the concrete walkways and so on
2. I could wait to post a single link until we have a completely assembled plant

Unfortunately people cannot create their own links unless they have access to the files

**Comment by monroews** [comment]
Is there a way to give read only access to the files? It would be nice if the drawing side of AIDE were open in a way that is similar to how github is open.

**Comment by eak24** [comment]
When template is done they will move the designs to github

**Comment by oliver-leung** [comment]
Closing due to transition to Onshape.
